[project]
name = "jetracer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "adafruit-pca9685>=1.0.1",
    "board>=1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
]
